---
kind: pipeline
name: "Push"

steps:
  - name: "Build Docker image"
    image: plugins/docker
    settings:
      tag: ${DRONE_COMMIT:0:7}
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
